version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        volumes:
            - ./dist/:/usr/share/nginx/html/
        ports:
            - "80:80"